import os

env = Environment(ENV = {'PATH':os.environ['PATH']})
env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g'])

env.Program("ratesFBF", "ratesFBF.C")
env.Program("ratesRBR", "ratesRBR.C")
env.Program('readFilesWithEntryNumber','readFilesWithEntryNumber.C')
