import os

env = Environment(ENV = {'PATH':os.environ['PATH']})

env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g'])

env.Program('gppCalibration','gppCalibration.C')
env.Program('gppTOFStudy','gppTOFStudy.C')